name = "vocarchive"
main = "src/app/index.ts"
compatibility_date = "2025-07-12"
assets = { directory = "./public" }
compatibility_flags = [
	"nodejs_compat"
]


[[d1_databases]]
binding = "DB"
database_name = "vocarchive_database"
database_id = ""