name = "vocarchive"
main = "src/app/index.tsx"
compatibility_date = "2025-07-12"
assets = { directory = "./public" }
compatibility_flags = [
	"nodejs_compat"
]


[[d1_databases]]
binding = "DB"
database_name = "vocarchive_database"
database_id = "da2b8ae3-53df-43e2-8b42-9af552ab81d6"