name = "vocarchive"
main = "src/app/index.ts"
compatibility_date = "2025-07-12"
assets = { directory = "./public" }
compatibility_flags = [
	"nodejs_compat"
]


[[d1_databases]]
binding = "DB"
database_name = "vocarchive_offical_deploy_database"
database_id = "ec0a34ea-2e41-4cc4-831e-6b9f4c5808ae"